### ISSUE TITLE
server.exe crashes on fresh install of 2.0.2

### ISSUE THREAD

**Issue by profucius** [elblogbruno/NotionAI-MyMind#12]
Hey man, got a new odd one for you. I downloaded your newest 2.0.2 today. To be safe, I totally uninstalled the previous version, and deleted any temp folders (.keras and .notion-py) to clean the slate. I installed 2.0.2 and launched server.exe. It asks me for the port, and then immediately crashes. I've uninstalled and reinstalled multiple times but receiving the same issue.

Here is the bit in the console right before it crashes:

---------------

Traceback (most recent call last):
  File "server.py", line 181, in <module>
  File "NotionAI\NotionAI.py", line 24, in __init__
    open_browser_at_start(port)
TypeError: open_browser_at_start() missing 1 required positional argument: 'port'
[32324] Failed to execute script server

**Comment by elblogbruno** [comment]
What a fast response!

That is a strange issue , I have fixed this issue today. May you please try downloading the latest, latest installer?

Sorry for it, but I had modified the published installer some times today before the final release.

**Comment by profucius** [comment]
I just re-downloaded this version from 1 hour ago, same issue. Did you upload a newer version than this that I am not seeing?

![image](https://user-images.githubusercontent.com/18254607/110359058-06158000-800b-11eb-805b-2729ece020ee.png)

**Comment by elblogbruno** [comment]
So strange I did delete the release because I was to fast and hadn't fix a bug yet and release it again .

**Comment by elblogbruno** [comment]
Give a sec I see what is happening

**Comment by profucius** [comment]
No worries, take your time

**Comment by elblogbruno** [comment]
Ok I feel I know the issue. Did create the installer before the bugfix 🤦‍♂️ 
I will update the installer now.
Sorry for it!

**Comment by elblogbruno** [comment]
Please re-download the installer again and see if it is fixed.

**Comment by profucius** [comment]
Alright, that solved that problem! However it seems that I cannot test it out until the browser extension stores are updated. You said you submitted them, but Chrome says it hasn't been updated since Mar 3 and Firefox says it was updated 5 hours ago. I may have to wait longer for Chrome to approve your update.

I tried testing it with Firefox, but it seems that nothing happens. I uninstalled and reinstalled the Firefox addon from the addons page (says updated 5 hours ago). I configure it with the server IP:PORT (as I did with previous versions). However when I try to capture text or capture a whole page, But nothing happens.

I've verified that the extension is connected. If I go to the server IP:PORT in a new tab, the server.exe console log shows the GET successfully

[2021-03-08 13:34:11,283] 192.168.1.135:55486 GET / 1.1 200 5974 8977

But when I try to capture text, the server.exe console log does not show any changes. And there is no error or popup in the webpage.

Maybe the Firefox extension is not up to date on the addons page?

**Comment by elblogbruno** [comment]
Ok, Thanks for the feedback. As you said, the chrome extension takes longer to publish as google revises it in case it has any privacy or virus. In Firefox, the extension update is published in minutes.
I will try to reproduce your error.

**Comment by elblogbruno** [comment]
Dumb question from my part.
Have you tried refreshing the collection? This needs to be done every time you add a collection. Before it was done when the website loaded, but it made many requests to the notion API, so it was not a very good idea.
![image](https://user-images.githubusercontent.com/10481058/110369230-624bc480-804a-11eb-8354-f406473328dd.png)

**Comment by profucius** [comment]
Just tried that, and I get this error:

------------

[2021-03-08 15:11:30,852] Running on http://0.0.0.0:6767 (CTRL + C to quit)
[2021-03-08 15:11:34,318] ERROR in app: Exception on request GET /get_mind_structure
Traceback (most recent call last):
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 61, in get_mind_structure
AttributeError: 'NotionAI' object has no attribute 'mind_structure'
[2021-03-08 15:11:34,320] Error in ASGI Framework
Traceback (most recent call last):
  File "hypercorn\asyncio\context.py", line 39, in _handle
  File "hypercorn\utils.py", line 239, in invoke_asgi
  File "quart\app.py", line 2117, in __call__
  File "quart\app.py", line 2140, in asgi_app
  File "quart\asgi.py", line 33, in __call__
  File "quart\asgi.py", line 256, in _raise_exceptions
  File "quart\asgi.py", line 72, in handle_request
  File "quart\app.py", line 1866, in handle_request
  File "quart\app.py", line 1118, in handle_exception
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 61, in get_mind_structure
AttributeError: 'NotionAI' object has no attribute 'mind_structure'
[2021-03-08 15:11:34,322] 192.168.1.135:60961 GET /get_mind_structure 1.1 500 - 6981

**Comment by elblogbruno** [comment]
Please, could you try putting your credentials again and then refreshing again?

**Comment by profucius** [comment]
Yessir, same issue unfortunately. I even tried using my Token v2 instead of credentials. This is what I get when using token:

----------

Login in with tokenV2
[2021-03-08 16:02:25,650] 192.168.1.135:60425 POST /handle_data 1.1 200 3 4301447
[2021-03-08 16:02:29,985] ERROR in app: Exception on request GET /get_mind_structure
Traceback (most recent call last):
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 61, in get_mind_structure
  File "NotionAI\mind_structure.py", line 25, in get_mind_structure
    structure = self.client.get_block(structure_url)
  File "notion\client.py", line 169, in get_block
  File "notion\client.py", line 162, in get_record_data
  File "notion\store.py", line 184, in get
  File "notion\store.py", line 286, in call_load_page_chunk
  File "notion\client.py", line 260, in post
requests.exceptions.HTTPError: Invalid input.
[2021-03-08 16:02:29,987] Error in ASGI Framework
Traceback (most recent call last):
  File "hypercorn\asyncio\context.py", line 39, in _handle
  File "hypercorn\utils.py", line 239, in invoke_asgi
  File "quart\app.py", line 2117, in __call__
  File "quart\app.py", line 2140, in asgi_app
  File "quart\asgi.py", line 33, in __call__
  File "quart\asgi.py", line 256, in _raise_exceptions
  File "quart\asgi.py", line 72, in handle_request
  File "quart\app.py", line 1866, in handle_request
  File "quart\app.py", line 1118, in handle_exception
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 61, in get_mind_structure
  File "NotionAI\mind_structure.py", line 25, in get_mind_structure
    structure = self.client.get_block(structure_url)
  File "notion\client.py", line 169, in get_block
  File "notion\client.py", line 162, in get_record_data
  File "notion\store.py", line 184, in get
  File "notion\store.py", line 286, in call_load_page_chunk
  File "notion\client.py", line 260, in post
requests.exceptions.HTTPError: Invalid input.
[2021-03-08 16:02:29,990] 192.168.1.135:60425 GET /get_mind_structure 1.1 500 - 124674

**Comment by elblogbruno** [comment]
Ok I see what is happening

As I have said on the release text and changelog, notion API has changed and so it affects notion-py, which is the library I use to interact with notion.

The fix is in here https://github.com/jamalex/notion-py/issues/292 but you need to modify manually the library. In case of the windows installer, I haven't found a way yet to manually modify the library files.  Meanwhile, I am waiting for the library owner to update it.

I am sorry for it, but it is not  my fault, unfortunately,

**Comment by elblogbruno** [comment]
ok may have find a temporal solution so you don't have to do anything. Wait a sec.

**Comment by elblogbruno** [comment]
Ok, I am rebuilding the installer. I did made a fork and modified the library myself and packed it in on the project. Once the new installer is uploaded reinstall the server, put your credentials in, refresh the collections and you should be ready to enjoy!!

**Comment by elblogbruno** [comment]
Whenever you want you can download the latest installer!
Hope it works this time.

**Comment by profucius** [comment]
Ok I will give it a try. I am still seeing the 2.0.2 release from earlier today https://github.com/elblogbruno/NotionAI-MyMind/tree/2.0.2

Do you want me to just download the server installer from within that release? Or did you create a separate release tag for the fix?

**Comment by elblogbruno** [comment]
I did updated the installer on that release, so people don't get confused.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by elblogbruno** [comment]
Hi,
Good Morning
How did it go?

**Comment by elblogbruno** [comment]
Don't worry! Take your time!

**Comment by profucius** [comment]
Hmm, strangely I am still getting the same error. I just re-downloaded the latest server installer package again, installed over what I already had configured, ran server and it started fine. Clicked on "refresh collections" and received this (which looks the same as yesterday)

-----------

[2021-03-09 10:16:19,705] Running on http://0.0.0.0:6767 (CTRL + C to quit)
[2021-03-09 10:16:25,319] ERROR in app: Exception on request GET /get_mind_structure
Traceback (most recent call last):
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 61, in get_mind_structure
  File "NotionAI\mind_structure.py", line 25, in get_mind_structure
    structure = self.client.get_block(structure_url)
  File "notion\client.py", line 169, in get_block
  File "notion\client.py", line 162, in get_record_data
  File "notion\store.py", line 184, in get
  File "notion\store.py", line 286, in call_load_page_chunk
  File "notion\client.py", line 260, in post
requests.exceptions.HTTPError: Invalid input.
[2021-03-09 10:16:25,322] Error in ASGI Framework
Traceback (most recent call last):
  File "hypercorn\asyncio\context.py", line 39, in _handle
  File "hypercorn\utils.py", line 239, in invoke_asgi
  File "quart\app.py", line 2117, in __call__
  File "quart\app.py", line 2140, in asgi_app
  File "quart\asgi.py", line 33, in __call__
  File "quart\asgi.py", line 256, in _raise_exceptions
  File "quart\asgi.py", line 72, in handle_request
  File "quart\app.py", line 1866, in handle_request
  File "quart\app.py", line 1118, in handle_exception
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 61, in get_mind_structure
  File "NotionAI\mind_structure.py", line 25, in get_mind_structure
    structure = self.client.get_block(structure_url)
  File "notion\client.py", line 169, in get_block
  File "notion\client.py", line 162, in get_record_data
  File "notion\store.py", line 184, in get
  File "notion\store.py", line 286, in call_load_page_chunk
  File "notion\client.py", line 260, in post
requests.exceptions.HTTPError: Invalid input.
[2021-03-09 10:16:25,324] 192.168.1.135:50051 GET /get_mind_structure 1.1 500 - 379743

**Comment by profucius** [comment]
Looks like that second to last line indicates that the notion-py file is the older one, before the fix over at notion-py repo?

**Comment by elblogbruno** [comment]
Hi! I am back!
Could you download latest installer? It has worked on my computer now.

**Comment by elblogbruno** [comment]
I am so glad!
Hope you like it!
Next step is implementing idea number 1 and 2

**Comment by profucius** [comment]
Thanks for your hard work and determination! I'll close this ticket out now that it's resolved.
