### ISSUE TITLE
Error! Notion Credentials are incorrect. Please check you have enter the correct tokenV2 or email and password.

### ISSUE THREAD

**Issue by bibek-maharjan** [elblogbruno/NotionAI-MyMind#19]
I get the following error.

[2021-05-21 11:06:19,603] ERROR in app: Exception on request POST /handle_data
Traceback (most recent call last):
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 290, in handle_data
  File "NotionAI\NotionAI.py", line 60, in run
  File "image_tagging\image_tagging.py", line 21, in __init__
ValueError: could not convert string to float: ''
Exception on request POST /handle_data
Traceback (most recent call last):
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 290, in handle_data
  File "NotionAI\NotionAI.py", line 60, in run
  File "image_tagging\image_tagging.py", line 21, in __init__
ValueError: could not convert string to float: ''
Executing <Task finished name='Task-25' coro=<ASGIHTTPConnection.handle_request() done, defined at quart\asgi.py:70> exception=ValueError("could not convert string to float: ''") created at quart\asgi.py:28> took 1.532 seconds
Error in ASGI Framework
Traceback (most recent call last):
  File "hypercorn\asyncio\context.py", line 39, in _handle
  File "hypercorn\utils.py", line 239, in invoke_asgi
  File "quart\app.py", line 2117, in __call__
  File "quart\app.py", line 2140, in asgi_app
  File "quart\asgi.py", line 33, in __call__
  File "quart\asgi.py", line 256, in _raise_exceptions
  File "quart\asgi.py", line 72, in handle_request
  File "quart\app.py", line 1866, in handle_request
  File "quart\app.py", line 1118, in handle_exception
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 290, in handle_data
  File "NotionAI\NotionAI.py", line 60, in run
  File "image_tagging\image_tagging.py", line 21, in __init__
ValueError: could not convert string to float: ''
[2021-05-21 11:06:19,621] Error in ASGI Framework
Traceback (most recent call last):
  File "hypercorn\asyncio\context.py", line 39, in _handle
  File "hypercorn\utils.py", line 239, in invoke_asgi
  File "quart\app.py", line 2117, in __call__
  File "quart\app.py", line 2140, in asgi_app
  File "quart\asgi.py", line 33, in __call__
  File "quart\asgi.py", line 256, in _raise_exceptions
  File "quart\asgi.py", line 72, in handle_request
  File "quart\app.py", line 1866, in handle_request
  File "quart\app.py", line 1118, in handle_exception
  File "quart\app.py", line 1862, in handle_request
  File "quart\app.py", line 1887, in full_dispatch_request
  File "quart\app.py", line 1104, in handle_user_exception
  File "quart\app.py", line 1885, in full_dispatch_request
  File "quart\app.py", line 1933, in dispatch_request
  File "server.py", line 290, in handle_data
  File "NotionAI\NotionAI.py", line 60, in run
  File "image_tagging\image_tagging.py", line 21, in __init__
ValueError: could not convert string to float: ''
[2021-05-21 11:06:19,631] 192.168.1.102:3859 POST /handle_data 1.1 500 - 1567115
192.168.1.102:3859 POST /handle_data 1.1 500 - 1567115

**Comment by elblogbruno** [comment]
Hi!
How did you write the confidence threshold number?

It should be a normal number not inside 
'  '

As well it should be a decimal number like for example 0.10 (that it's 10%)

As well just to make sure, are you using the latest version of the server?

As well just to check is not a bug, if you don't enter any number , the default one is 0.20 (20%) you can try that and see if it does not give any error.

Hope you get it working
Cordially
Bruno

**Comment by bibek-maharjan** [comment]
Thank you so much 🙏, adding 0.20 solved the issue.
Previously, I left it empty which caused the issue.

**Comment by elblogbruno** [comment]
Nice!
Hope you enjoy it!
Have a nice day!
